# Generated by Django 2.1.2 on 2018-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='course',
        ),
    ]
