# Generated by Django 2.1.2 on 2018-10-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20181024_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Географические данные', 'verbose_name_plural': 'Географические данные'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
