# Generated by Django 2.1.2 on 2018-10-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20181024_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='card.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Языковые курсы'), (2, 'Танцевальные курсы'), (3, 'Вокальные курсы'), (4, 'Курсы ораторского искусства')], default=1, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[(1, 'Телефон'), (2, 'Facebook'), (3, 'e-mail')], default=1, verbose_name='Варианты'),
        ),
    ]
