# Generated by Django 2.1.2 on 2018-10-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20181030_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='card.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
